export enum TypesOfDocuments {
  INVOICE = "INVOICE",
  QUOTATION = "QUOTATION",
  DELIVERY_ORDER = "DELIVERY_ORDER",
  PURCHASE_ORDER = "PURCHASE_ORDER",
  CREDIT_NOTE = "CREDIT_NOTE",
  DEBIT_NOTE = "DEBIT_NOTE",
  RECEIPT = "RECEIPT",
  PAYMENT = "PAYMENT",
  EXPENSE = "EXPENSE",
}
